FROM node:22-alpine

WORKDIR /app
RUN npm i -g husky pnpm@9
COPY pnpm-lock.yaml package.json ./
RUN pnpm i --frozen-lockfile
COPY . .
RUN pnpm build && \
	pnpm prune --prod

EXPOSE 3000
ENV NODE_PORT=3000
ENV NODE_ENV=dev
CMD [ "dist/main.js" ]
